[package]
name = "htpc_app_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.22"
egui_extras = { version = "0.22", features = ["image"] }
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
shellexpand = "3.1"
chrono = "0.4"
